version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    depends_on:
      - sqlserver
    volumes:
      - ..:/app
    working_dir: /app/TodoAPI 
    command: ["dotnet", "run"] 
    ports:
      - "8080:5083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5083
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Todos;User Id=sa;Password=Password123;TrustServerCertificate=True;
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password123", "-Q", "SELECT 1"]
      interval: 5s
      retries: 3